/* ============================================================
   data.js — Application state (v3 "Dashboard" concept)
   ============================================================
   All card and notification data lives here, separate from
   rendering and behavior. Three global objects:

     AppData   — the "database": saved tasks/keep, notifications
     UIState   — transient UI state: active screen, dashboard
                 expand states, what's being edited
     DataHelpers — CRUD + dashboard utilities used by app.js

   v3 model changes vs v1/v2:
   - No inbox/confirm flow. LLM output lands directly in
     savedTasks / savedKeep with isNew: true (auto-apply).
   - Accepted tasks can receive LLM updates: the item data is
     already updated (auto-apply), and item.updates[] records
     what changed so the UI can show a diff.
   - Notifications carry category: "primary" | "social" for the
     sidebar categorization.

   No DOM access in this file. Pure data.
   ============================================================ */

var AppData = {
  /* Inbox arrays kept for compatibility with shared helpers.
     Unused in v3 — new items land directly in saved arrays. */
  tasks: [],
  keep: [],

  savedTasks: [
    {
      id: "task-1",
      title: "Plan the quarterly product roadmap review",
      contents:
        "Coordinate with stakeholders to schedule and prepare materials for the Q3 product review session",
      date: "2026-07-09",
      time: "10:00",
      state: "task",
      status: "active",
      pinned: true,
      isNew: false,
      updates: [],
      sourceNotifIds: [],
      subtasks: [
        { id: "st-1a", label: "Send calendar invites", checked: true },
        { id: "st-1b", label: "Prepare slide deck", checked: false },
      ],
      visibleCount: null,
    },
    {
      id: "task-2",
      title: "Finalize the Q3 marketing assets",
      contents:
        "Coordinate with design and copywriting to finalize all campaign assets before the launch date, including social graphics, landing page, and email sequence",
      date: "",
      time: "",
      state: "task",
      status: "active",
      pinned: false,
      isNew: false,
      updates: [],
      sourceNotifIds: [],
      subtasks: [
        {
          id: "st-2a",
          label:
            "Design and finalize all social media graphics across every platform for the launch",
          checked: false,
        },
        {
          id: "st-2b",
          label:
            "Write and review all campaign copy with marketing and legal teams before the deadline",
          checked: false,
        },
        {
          id: "st-2c",
          label:
            "Coordinate with the legal team to review all claims made in the campaign messaging",
          checked: false,
        },
        {
          id: "st-2d",
          label:
            "Schedule the email sequence and confirm send times across all time zones",
          checked: false,
        },
      ],
      visibleCount: 2,
    },
    {
      id: "task-3",
      title: "Review onboarding flow updates",
      contents:
        "Walk through the updated onboarding flow with the design team and leave feedback before Thursday",
      date: "",
      time: "",
      state: "task",
      status: "active",
      pinned: false,
      isNew: true, // newly generated by the LLM — shows "New" chip + dashboard count
      updates: [],
      sourceNotifIds: ["notif-1"],
      subtasks: [
        { id: "st-3a", label: "Read the Figma file", checked: false },
        { id: "st-3b", label: "Leave inline comments", checked: false },
      ],
      visibleCount: null,
    },
    {
      id: "task-4",
      title: "RSVP and prep for July team offsite",
      /* This task was auto-updated by the LLM from notif-6 (Lisa's
         follow-up email). The fields below are the POST-update
         values; updates[0] records what changed. */
      contents:
        "Confirm attendance by July 12, book B2 parking spot, bring laptop and charger. The Greenhouse on Xinyi Rd, July 18–19.",
      date: "2026-07-12",
      time: "",
      state: "task",
      status: "active",
      pinned: false,
      isNew: false,
      updates: [
        {
          id: "upd-1",
          time: "10m ago",
          sourceNotifId: "notif-6",
          sourceApp: "Gmail",
          seen: false,
          changes: [
            { type: "date", from: "2026-07-10", to: "2026-07-12" },
            {
              type: "subtask-added",
              label: "Submit dietary preferences form",
            },
          ],
        },
      ],
      sourceNotifIds: ["notif-4"],
      subtasks: [
        { id: "st-4a", label: "RSVP by July 12", checked: false },
        { id: "st-4b", label: "Book parking spot at B2", checked: false },
        {
          id: "st-4c",
          label: "Submit dietary preferences form",
          checked: false,
          addedByUpdate: "upd-1", // highlighted amber while the update is unseen
        },
      ],
      visibleCount: null,
    },
  ],

  savedKeep: [
    {
      id: "keep-1",
      title: "API rate limits update — v3 deprecation",
      contents:
        "New rate limits effective July 1: 500 req/min for standard tier, 2000 req/min for premium. API v2 endpoints deprecated August 15 — all integrations must migrate to v3 by then.",
      date: "2026-07-01",
      time: "",
      state: "keep",
      status: "saved",
      pinned: false,
      isNew: true, // newly generated by the LLM
      updates: [],
      sourceNotifIds: ["notif-3"],
      subtasks: [
        {
          id: "st-k1a",
          label: "Audit current v2 endpoint usage",
          checked: false,
        },
        {
          id: "st-k1b",
          label: "Update integration to v3 endpoints",
          checked: false,
        },
        {
          id: "st-k1c",
          label: "Verify rate limit headroom on standard tier",
          checked: false,
        },
      ],
      visibleCount: 2,
    },
    {
      id: "keep-2",
      title: "Team offsite — venue and logistics",
      contents:
        "Offsite confirmed for July 18–19 at The Greenhouse, 45 Xinyi Rd. Day 1 starts at 9:30 AM with breakfast provided. Bring laptop and charger. Parking available at B2 level, entrance on Keelung Rd side.",
      date: "2026-07-18",
      time: "09:30",
      state: "keep",
      status: "saved",
      pinned: true,
      isNew: false,
      updates: [],
      sourceNotifIds: ["notif-4"],
      subtasks: [
        { id: "st-k2a", label: "RSVP by July 10", checked: false },
        { id: "st-k2b", label: "Book parking spot", checked: false },
      ],
      visibleCount: null,
    },
  ],

  notifications: [
    {
      id: "notif-6",
      app: "Gmail",
      icon: "ti-mail",
      logoClass: "gmail",
      subtitle: "Lisa Huang &middot; Operations",
      time: "10m ago",
      timestamp: "2026-07-07T15:40:00",
      category: "primary",
      contents:
        "Quick update on the offsite — RSVP deadline is extended to July 12, and please fill in the dietary preferences form I just shared so catering can be finalized.",
    },
    {
      id: "notif-1",
      app: "Slack",
      icon: "ti-brand-slack",
      logoClass: "slack",
      subtitle: "#product-design &middot; Maria Chen",
      time: "25m ago",
      timestamp: "2026-07-07T15:25:00",
      category: "primary",
      contents:
        "Hey team, I just pushed the updated mockups for the notification card redesign, can everyone take a look before our sync tomorrow and leave comments",
    },
    {
      id: "notif-2",
      app: "Telegram",
      icon: "ti-brand-telegram",
      logoClass: "telegram",
      subtitle: "Design Team Group",
      time: "40m ago",
      timestamp: "2026-07-07T15:10:00",
      category: "social",
      contents:
        "Alex: Just shared the updated brand guidelines doc in the channel, let me know if you have questions before the workshop on Thursday",
    },
    {
      id: "notif-3",
      app: "Gmail",
      icon: "ti-mail",
      logoClass: "gmail",
      subtitle: "Kevin Wu &middot; Engineering",
      time: "1h ago",
      timestamp: "2026-07-07T14:45:00",
      category: "primary",
      contents:
        "Heads up — the platform team just published new API rate limits for v3. The v2 endpoints are being deprecated mid-August. Full details in the attached migration guide.",
    },
    {
      id: "notif-5",
      app: "Telegram",
      icon: "ti-brand-telegram",
      logoClass: "telegram",
      subtitle: "Mom",
      time: "2h ago",
      timestamp: "2026-07-07T13:50:00",
      category: "social",
      contents:
        "Don't forget dinner this Sunday! Your aunt is visiting and she's bringing the kids.",
    },
    {
      id: "notif-4",
      app: "Gmail",
      icon: "ti-mail",
      logoClass: "gmail",
      subtitle: "Lisa Huang &middot; Operations",
      time: "3h ago",
      timestamp: "2026-07-07T12:30:00",
      category: "primary",
      contents:
        "Hi all, venue for the July offsite is confirmed! The Greenhouse on Xinyi Rd, July 18–19. Breakfast and lunch provided both days. Please RSVP by the 10th so I can finalize the headcount.",
    },
  ],
};

var UIState = {
  activeScreen: "home",
  previousScreen: "home",
  editing: null, // { section: 'savedTasks'|'savedKeep', id: 'task-1' }
  dashboard: {
    summaryExpanded: false,
    summaryDismissed: false,
    openActivity: {}, // { 'task-4': true } — which activity diffs are expanded
    whatsNewVariant: "redesign", // "original" | "redesign"
    activityIndex: 0, // carousel position in the merged New + Updated feed
    activityFilters: { new: false, update: false }, // both off = show everything
    openUpdateCard: {}, // { 'task-4': true } — which update cards are expanded
  },
  sections: {
    tasks: { collapsed: false },
    keep: { collapsed: false },
  },
  filters: {
    tasks: "active", // "active" | "completed"
    keep: "saved", // "saved" | "archived"
  },
};

/* ---------- Data helpers ---------- */

var DataHelpers = {
  find: function (section, id) {
    var arr = AppData[section];
    if (!arr) return null;
    for (var i = 0; i < arr.length; i++) {
      if (arr[i].id === id) return arr[i];
    }
    return null;
  },

  findIndex: function (section, id) {
    var arr = AppData[section];
    if (!arr) return -1;
    for (var i = 0; i < arr.length; i++) {
      if (arr[i].id === id) return i;
    }
    return -1;
  },

  remove: function (section, id) {
    var idx = this.findIndex(section, id);
    if (idx !== -1) return AppData[section].splice(idx, 1)[0];
    return null;
  },

  generateId: function (prefix) {
    return (
      prefix +
      "-" +
      Date.now().toString(36) +
      "-" +
      Math.random().toString(36).substr(2, 4)
    );
  },

  // Find a subtask by id across all items in a section
  findSubtask: function (section, subtaskId) {
    var arr = AppData[section];
    if (!arr) return null;
    for (var i = 0; i < arr.length; i++) {
      var sts = arr[i].subtasks || [];
      for (var j = 0; j < sts.length; j++) {
        if (sts[j].id === subtaskId) return sts[j];
      }
    }
    return null;
  },

  // Recalculate visibleCount heuristic after subtask edits
  refreshVisibleCount: function (item) {
    var total = (item.subtasks || []).length;
    if (total > 3) {
      item.visibleCount = 2;
    } else {
      item.visibleCount = null;
    }
  },

  // Map chip state value ('task'/'keep') to data section key ('tasks'/'keep')
  stateToSection: function (state) {
    return state === "task" ? "tasks" : "keep";
  },

  // Map chip state to saved-data section key
  stateToSavedSection: function (state) {
    return state === "task" ? "savedTasks" : "savedKeep";
  },

  /* ---------- v3 dashboard helpers ---------- */

  // "Morning" (5–12), "Afternoon" (12–18), "Evening" (otherwise)
  dayPart: function () {
    var h = new Date().getHours();
    if (h >= 5 && h < 12) return "Morning";
    if (h >= 12 && h < 18) return "Afternoon";
    return "Evening";
  },

  // Most recent notifications for the summary digest (data is
  // already ordered newest-first), capped at max
  getSummaryNotifs: function (max) {
    return AppData.notifications.slice(0, max);
  },

  // Unique app logos for the digest icon cluster (max 3)
  getSummaryApps: function () {
    var seen = {};
    var apps = [];
    for (var i = 0; i < AppData.notifications.length; i++) {
      var n = AppData.notifications[i];
      if (!seen[n.app]) {
        seen[n.app] = true;
        apps.push(n);
      }
      if (apps.length === 3) break;
    }
    return apps;
  },

  getNotifsByCategory: function (category) {
    return AppData.notifications.filter(function (n) {
      return n.category === category;
    });
  },

  // Counts for the "What's new" chips
  getNewCounts: function () {
    var count = function (arr) {
      return arr.filter(function (item) {
        return item.isNew;
      }).length;
    };
    return { tasks: count(AppData.savedTasks), keep: count(AppData.savedKeep) };
  },

  // Saved tasks that carry unseen LLM updates (amber entries)
  getUpdatedTasks: function () {
    return AppData.savedTasks.filter(function (item) {
      return (item.updates || []).some(function (u) {
        return !u.seen;
      });
    });
  },

  // Pinned items across both saved arrays, tasks first
  getPinned: function () {
    var out = [];
    AppData.savedTasks.forEach(function (item) {
      if (item.pinned) out.push({ section: "savedTasks", item: item });
    });
    AppData.savedKeep.forEach(function (item) {
      if (item.pinned) out.push({ section: "savedKeep", item: item });
    });
    return out;
  },

  // All new items (isNew: true) across tasks + keep, with section info
  getNewItems: function () {
    var items = [];
    AppData.savedTasks.forEach(function (item) {
      if (item.isNew) items.push({ section: "savedTasks", item: item });
    });
    AppData.savedKeep.forEach(function (item) {
      if (item.isNew) items.push({ section: "savedKeep", item: item });
    });
    return items;
  },

  // Single merged "What's new" feed: new items awaiting review first
  // (they need an explicit Approve/Edit/Delete decision), then already-
  // applied updates (informational only). Used by the dashboard carousel.
  getActivityEntries: function () {
    var entries = [];
    this.getNewItems().forEach(function (e) {
      entries.push({ kind: "new", section: e.section, item: e.item });
    });
    this.getUpdatedTasks().forEach(function (item) {
      entries.push({ kind: "update", section: "savedTasks", item: item });
    });
    return entries;
  },

  // getActivityEntries(), narrowed by the dashboard's New/Updated filter
  // chips. Both off (the default) shows everything.
  getVisibleActivityEntries: function () {
    var entries = this.getActivityEntries();
    var filters = UIState.dashboard.activityFilters;
    if (filters.new || filters.update) {
      entries = entries.filter(function (e) {
        return filters[e.kind];
      });
    }
    return entries;
  },

  // v3: "confirm" an item — clear isNew flag (items are already in saved arrays)
  confirmItem: function (section, id, newState) {
    var item = this.find(section, id);
    if (!item) {
      // Try saved arrays directly
      item = this.find("savedTasks", id) || this.find("savedKeep", id);
    }
    if (item) {
      item.isNew = false;
      item.state = newState;
    }
  },

  // Find the notification object by id
  findNotification: function (notifId) {
    for (var i = 0; i < AppData.notifications.length; i++) {
      if (AppData.notifications[i].id === notifId) return AppData.notifications[i];
    }
    return null;
  },

  // Collect all unseen changes across an item's updates, with source info
  getUnseenChangeSummary: function (item) {
    var unseen = (item.updates || []).filter(function (u) { return !u.seen; });
    var allChanges = [];
    var sources = [];
    var seenSources = {};
    unseen.forEach(function (u) {
      u.changes.forEach(function (c) { allChanges.push(c); });
      if (u.sourceNotifId && !seenSources[u.sourceNotifId]) {
        seenSources[u.sourceNotifId] = true;
        sources.push({ notifId: u.sourceNotifId, app: u.sourceApp, time: u.time });
      }
    });
    return { changes: allChanges, sources: sources, latest: unseen[unseen.length - 1] };
  },

  // Short preview text for collapsed update card
  describeChangesPreview: function (changes) {
    var labels = changes.map(function (c) {
      if (c.type === "date") return "Date changed";
      if (c.type === "subtask-added") return "Sub-task added";
      if (c.type === "subtask-removed") return "Sub-task removed";
      if (c.type === "location") return "Venue added";
      return "Updated";
    });
    // Deduplicate
    var seen = {};
    var unique = [];
    labels.forEach(function (l) {
      if (!seen[l]) { seen[l] = true; unique.push(l); }
    });
    return unique.join(", ");
  },

  // Human-readable line for one update change entry
  describeChange: function (change) {
    if (change.type === "date") {
      return "Date changed: " + change.from + " → " + change.to;
    }
    if (change.type === "subtask-added") {
      return "Sub-task added: “" + change.label + "”";
    }
    if (change.type === "subtask-removed") {
      return "Sub-task removed: “" + change.label + "”";
    }
    return "Updated";
  },
};
